function valid = is_valid_position(pos, s)
    % Check if position is within bounds
    valid = pos(1) >= s.x_min && pos(1) <= s.x_max && ...
            pos(2) >= s.y_min && pos(2) <= s.y_max && ...
            pos(3) >= s.z_min && pos(3) <= s.z_max && ...
            sqrt(pos(1)^2 + pos(2)^2) <= s.x_max;
end